sonar.projectKey=asangaindunil_7.3H
sonar.organization=asanga-indunil
sonar.host.url=https://sonarcloud.io
sonar.projectName=Smart Task Management API
sonar.sourceEncoding=UTF-8

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/dto/**,**/entity/**,**/*Application.java
